# Configura\u00e7\u00e3o do Servidor Web (Mudando da porta padr\u00e3o 8080 para 8081 para evitar conflitos)
server.port=8081

# Configura\u00e7\u00e3o de Conex\u00e3o com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gerencia
spring.datasource.username=postgres
spring.datasource.password=levy0102
spring.datasource.driver-class-name=org.postgresql.Driver

# O Hibernate vai criar e atualizar as tabelas automaticamente baseado no nosso Model
spring.jpa.hibernate.ddl-auto=update

# Mostra no console (terminal) os comandos SQL que o Hibernate est\u00e1 gerando
spring.jpa.show-sql=true